Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.network "public_network", bridge: "vagrant"
    config.vm.provider "hyperv" do |hyperv|
        hyperv.cpus = 2
        hyperv.memory = 2048
        # allow nested virtualization
        # egrep -c '(vmx|svm)' /proc/cpuinfo
        # sudo kvm-ok
        hyperv.enable_virtualization_extensions = true
    end
end

